# Generated by Django 3.1.7 on 2023-11-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpaddle', '0005_auto_20231118_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='original_subscriber_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
