# Generated by Django 3.1.7 on 2023-11-17 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djpaddle', '0006_subscription_original_subscriber_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='original_subscriber_id',
            new_name='original_subscription_id',
        ),
    ]
