# Generated by Django 3.1.7 on 2023-11-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djpaddle', '0007_auto_20231118_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='original_subscription_id',
            field=models.IntegerField(default=0),
        ),
    ]
