# Generated by Django 3.1.7 on 2023-11-17 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djpaddle', '0008_auto_20231118_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='original_subscription_id',
        ),
    ]
